#!/bin/bash
# Simple script to gather log information
LOG=/tmp/debug.log.tmp

touch $LOG
lsusb &> $LOG
echo "===========================" >> $LOG
df -h &>> $LOG
echo "===========================" >> $LOG
iw dev &>> $LOG
echo "===========================" >> $LOG
ifconfig -a &>> $LOG
echo "===========================" >> $LOG
/usr/bin/pineapple/site_survey 15 >> $LOG
echo "===========================" >> $LOG
dmesg &>> $LOG
mv $LOG /tmp/debug.log