#!/bin/bash

checkInternet() {
    ping -c1 -W3 -q 8.8.8.8 &> /dev/null && {
        echo "1"
    } || {
        echo "0"
    }
}

checkSDCard() {
    [[ $(mount | grep /sd) == "" ]] && {
        echo "0"
    } || {
        echo "1"
    }
}


sendEmail() {
    tar_gz=$1
    to=$(uci get reporting.ssmtp.to)
    from=$(uci get reporting.ssmtp.from)
    email_body="To:$to\nFrom:$from\nSubject:WiFi Pineapple Report: $(date)\n\nPlease see the attached file."

    date=$(date +%Y-%m-%d-%H:%M)

    echo -e $email_body | (cat - && cat $tar_gz | uuencode "WiFi_Pineapple_Report_$(date +%Y-%m-%d-%H-%M).tar.gz") | ssmtp $to  &> /dev/null && {
        echo "$date: Successfully sent email to $to" >> /tmp/reporting.log
    } || {
        echo "$date: Failed to send email to $to" >> /tmp/reporting.log
    }
}

getPineAPReport() {
    [[ "$(uci get reporting.settings.log)" == "1" ]] && {
        cp $(cat /etc/pineapple/pineap_log_location)pineap.log $tmpdir/report/pineap.log
        [[ "$(uci get reporting.settings.clear_log)" == "1" ]] && {
            echo "" > $(cat /etc/pineapple/pineap_log_location)pineap.log
        }
    }
}

getClientReport() {
    [[ "$(uci get reporting.settings.client)" == "1" ]] && {
        /usr/bin/pineapple/generate_probe_report > $tmpdir/report/probing_clients.csv
    }
}

getSiteReport() {
    [[ "$(uci get reporting.settings.survey)" == "1" ]] && {
        duration=$(uci get reporting.settings.duration)

        /usr/bin/pineapple/site_survey $duration > $tmpdir/report/site_survey
    }
}

getTrackedClients() {
    [[ "$(uci get reporting.settings.tracking)" == "1" ]] && {
        cp /tmp/tracking.report $tmpdir/report/tracked_clients &> /dev/null
        echo "" > /tmp/tracking.report
    }
}

generateReport() {
    rm -rf $tmpdir/report &> /dev/null
    mkdir -p $tmpdir/report &> /dev/null

    archive_name="WiFi_Pineapple_Report_$(date +%Y-%m-%d-%H-%M).tar.gz"

    getPineAPReport
    getClientReport
    getTrackedClients
    getSiteReport

    tar -C $tmpdir -pczhf $tmpdir/$archive_name report

    [[ "$(uci get reporting.settings.send_email)" == "1" ]] && {
        [[ "$(checkInternet)" == "1" ]] && {
            sendEmail $tmpdir/$archive_name
        } || {
            echo "$(date +%Y-%m-%d-%H:%M): Failed to email report - no internet connection available" >> /tmp/reporting.log
        }
    }

    [[ $(checkSDCard) == "1" ]] && {
        [[ "$(uci get reporting.settings.save_report)" != "1" ]] && {
            rm -rf $tmpdir/$archive_name
        } || {
            mkdir -p /sd/wifipineapple_reports &> /dev/null
            mv $tmpdir/$archive_name /sd/wifipineapple_reports/$archive_name
            echo "$(date +%Y-%m-%d-%H:%M): Report saved to SD card" >> /tmp/reporting.log
        }
    } || {
        echo "$(date +%Y-%m-%d-%H:%M): Failed to save to SD card - no SD card found" >> /tmp/reporting.log
    }

    rm -rf $tmpdir/report &> /dev/null
}

tmpdir="/tmp"
[[ $(checkSDCard) == "1" ]] && {
    tmpdir="/sd/tmp"
}

generateReport